# DB Version: 17
# OS Type: linux
# DB Type: web
# Total Memory (RAM): 1 GB
# CPUs num: 1
# Connections num: 200
# Data Storage: ssd

max_connections = 200
shared_buffers = 256MB
effective_cache_size = 1024MB			#-- effective_cache_size esta em 4G
maintenance_work_mem = 128MB			#-- o padrao e 64mb
checkpoint_completion_target = 0.9
wal_buffers = -1 						#-- configuracao -1 o banco gerencia o recurso
default_statistics_target = 100
random_page_cost = 1.1
effective_io_concurrency = 200
work_mem = 8MB 							#-- precisamos monitorar o comportamento pois o correto seria manter em 1.2MB
huge_pages = try
min_wal_size = 1GB
max_wal_size = 4GB
# LOGS DISABLE
# Desabilita logs de conexao/desconexao
log_connections = off
log_disconnections = off
# Desabilita logs de checkpoints e autovacuum
log_checkpoints = off
log_autovacuum_min_duration = -1
# habilita coletor de log
logging_collector = on
# Local dos logs e nome do arquivo,
log_directory = '/var/log/postgresql'
log_filename = 'postgresql-%Y-%m-%d.log'
# consultas com mais de 1h,
log_min_duration_statement = 3600000   # 1h em milissegundos
log_statement = 'none'
# log de warning e fatal error,
log_min_messages = warning
client_min_messages = warning
log_error_verbosity = terse     # nivel de verbosidade baixo - "terse": so erro, sem detalhes
log_line_prefix = '%t [%p] '
# calcula o tempo das consultas "lentas > log_min_duration_statement"
log_duration = off
# log-rotate
log_rotation_age = 1d          # gira a cada 1 dia (ou quando atingir o tamanho)
log_rotation_size = 1GB        # gira o log ao chegar em 1 GB
log_truncate_on_rotation = off
