## docker-compose.frontend.yaml — DSpace Angular (UI)
## Gerenciado pelo cctl — nao editar manualmente

networks:
  dspacenet:

services:
  dspace-angular:
    container_name: ${COMPOSE_PROJECT_NAME}-dspace-angular
    hostname: frontend
    restart: always
    environment:
      DSPACE_UI_SSL: 'false'
      DSPACE_UI_HOST: dspace-angular
      DSPACE_UI_PORT: '4000'
      DSPACE_UI_NAMESPACE: /
      DSPACE_REST_SSL: 'true'
      DSPACE_REST_HOST: ${DOMAIN_NAME}
      DSPACE_REST_PORT: 443
      DSPACE_REST_NAMESPACE: /server
    image: "${DOCKER_OWNER}/dspace-angular:${DSPACE_VER}"
    depends_on:
      - dspace
    volumes:
      - ../custom-dspace-angular/dist:/app/dist
      - ../custom-dspace-angular/angular.json:/app/angular.json
      - ../custom-dspace-angular/config/config.prod.yml:/app/config/config.prod.yml
      - ../custom-dspace-angular/docker/dspace-ui.json:/app/dspace-ui.json
      - frontend_logs:/app/logs
    deploy:
      resources:
        limits:
          memory: ${FRONTEND_MEMORY_LIMIT}
          cpus: ${FRONTEND_CPU_LIMIT}
    networks:
      dspacenet:
    stdin_open: true
    tty: true

volumes:
  frontend_logs:
